# Your workflow name.
name: Deploy to back4app.

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2


### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Release a Docker container to back4app. # Your custom step name
        uses: gonuit/back4app-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          # Below you must provide variables for your back4app app.

          # The email address associated with your back4app account.
          # If you don't want to use repository secrets (which is recommended) you can do:
          # email: my.email@example.com
          email: ${{ secrets.BACK4APP_EMAIL }}
          
          # back4app API key associated with provided user's email.
          # Api Key is available under your back4app account settings.
          back4app_api_key: ${{ secrets.BACK4APP_API_KEY }}
          
          # Name of the back4app application to which the build is to be sent.
          back4app_app_name: ${{ secrets.BACK4APP_APP_NAME }}

          # (Optional, default: "./")
          # Dockerfile directory.
          # For example, if you have a Dockerfile in the root of your project, leave it as follows:
          dockerfile_directory: ./

          # (Optional, default: "Dockerfile")
          # Dockerfile name.
          dockerfile_name: Dockerfile

          # (Optional, default: "")
          # Additional options of docker build command.
          docker_options: "--no-cache"

          # (Optional, default: "web")
          # Select the process type for which you want the docker container to be uploaded.
          # By default, this argument is set to "web".
          
          process_type: web
          
   
          
### ⬆ IMPORTANT PART ⬆ ###
